import requests

url = "http://172.26.16.90/danastudio/dodox/filemanager/file/upload"
header={"Authorization": "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjUwNTMyNDMsImlhdCI6MTU2NDQ0ODQ0MywiaXNzIjoiZGFuYXN0dWRpb19hdXRoX3NlcnZlciIsIm1vZHVsZXMiOlsiYWNjZXNzIiwiZGV2ZWxvcCIsIndvcmtmbG93IiwidmF1bHQiLCJkZXZjZW50ZXIiLCJvcGVyYXRpbmciXSwicm9sZV9pZCI6ImRldmVsb3BlciIsInJvbGVfbmFtZSI6IuW8gOWPkeiAhSIsInRrdmVyc2lvbiI6MSwidXNlcl9pZCI6IkFXcWFabUNoY2tVd0RSSTluUFZrIiwidXNlcl9uYW1lIjoiZGF0YXRvbSJ9.DXf9lUXGnuKtaDthdAkRLRbfrPYuk4Yzselx9DtBwe7MWCK0YgHKPOBBpk2ExJCUPMoaBu023kM1VTeqExJbgwjJL40esCK_Mb5L1fC1JENYgq1ZFiFr-raCslHKYHy13odXToaSoC3xAYWvaoQOyzQ3iFffaUGX4xFYTk264vS-PVO6KzNM35q-OB0gqcWTZw9Fqp3tTK8W-Y94G_deNIA2C6LJL-HxO2lNTsXS4X40PpDZMKhnLuqvwhYZQfGgeLxjQMtnw1xyFoQjJ1JiF1EYFGAasc_SSFp2T2WTaIza8sFi2bmuos2WJeCTnMu788jNGhnS71b5-JsjKfnFgIkrWuYS3SNweWiznbIG9wWe2rk_afvCrM89O2aPnKKDzp1Bf3I6ptkBLJ4wxrrlw17jG0gYyff4pSF0KQyxZfQi5WdsjSN3Jw7xSdqUUhX1MiyXoEdfJrYIe2oGRI7pweQgDtDEh50IFEUtvKymnoYqXR6wQJlzENC4_vikiFMvuP3DRdpTZY-r08rBFW1i_nGE5grgEh8yOneFIEH7VaxAx-tfxrEqUjh9_MxDfoqtDRZLqHJlOS5lXNMRph3D-a4dVbyXiPWweMnLkIaakHx3jnUfkSarzFHQRIT5QW4LwEP-mTUJ0GuIw1UkKBExgeOegK4GLTloGhLl5pAERJA"}
files = {'file':open('/opt/datatom/dana_api/execute_cfg/huanbaoju_16_87_test_origins_local.json','rb')}
upload_data={'filepath':'/var/dana/dodox/filemanager/file/admin/1','force':True}
upload_res=requests.post(url,upload_data,files=files,headers=header)

print(upload_res.text)

